language: go
go:
    - 1.9.x
sudo: required
services:
    - docker
before_install:
    - go get -u github.com/golang/dep/cmd/dep
    - go get -u github.com/mattn/goveralls
script:
    - cd $GOPATH/src/github.com/muka/mufaas && $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out
